# Generated by Django 4.1.5 on 2023-03-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('date', models.TimeField(max_length=250, verbose_name='Date')),
                ('equipment', models.TextField(verbose_name='Equipment')),
                ('country', models.TextField(verbose_name='Country')),
            ],
        ),
    ]
